/* eslint-disable */
/**
 * This file is auto-generated by the "npm run generate-runtime-index" command.
 * Do not modify this file directly.
 */
import import0 from "./AWS Account Management/check-organization-membership.js";
import import1 from "./AWS Account Management/check-security-contact.js";
import import2 from "./AWS App Runner/check-app-runner-vpc-endpoint.js";
import import3 from "./AWS AppSync/check-appsync-api-key-auth.js";
import import4 from "./AWS AppSync/check-appsync-cache-encryption.js";
import import5 from "./AWS AppSync/check-appsync-field-logging.js";
import import6 from "./AWS AppSync/check-appsync-graphql-api-tagged.js";
import import7 from "./AWS Backup/check-backup-plan-tagging.js";
import import8 from "./AWS Backup/check-backup-recovery-point-encryption.js";
import import9 from "./AWS Backup/check-backup-recovery-point-tags.js";
import import10 from "./AWS Backup/check-backup-report-plan-tags.js";
import import11 from "./AWS Backup/check-backup-vault-tags.js";
import import12 from "./AWS Batch/check-batch-cloudwatch-logs.js";
import import13 from "./AWS Batch/check-batch-role-config.js";
import import14 from "./AWS CloudFormation/check-cloudformation-stack-notifications.js";
import import15 from "./AWS CloudFormation/check-cloudformation-stack-tags.js";
import import16 from "./AWS CloudTrail/check-cloudtrail-bucket-access.js";
import import17 from "./AWS CloudTrail/check-cloudtrail-enabled.js";
import import18 from "./AWS CloudTrail/check-cloudtrail-encryption.js";
import import19 from "./AWS CloudTrail/check-cloudtrail-kms-encryption.js";
import import20 from "./AWS CloudTrail/check-cloudtrail-log-validation.js";
import import21 from "./AWS CloudTrail/check-cloudtrail-multiregion.js";
import import22 from "./AWS CloudTrail/check-cloudtrail-s3-access-logging.js";
import import23 from "./AWS CloudTrail/check-cloudtrail-tagged.js";
import import24 from "./AWS Config/check-config-enabled-all-regions.js";
import import25 from "./AWS Elastic Beanstalk/check-beanstalk-persistent-logs.js";
import import26 from "./AWS Elastic Beanstalk/check-elastic-beanstalk-access-logs.js";
import import27 from "./AWS Elastic Beanstalk/check-elastic-beanstalk-health.js";
import import28 from "./AWS Elastic Beanstalk/check-elastic-beanstalk-https.js";
import import29 from "./AWS Elastic Beanstalk/check-elastic-beanstalk-managed-updates.js";
import import30 from "./AWS Key Management Service/check-iam-kms-decrypt-policy.js";
import import31 from "./AWS Key Management Service/check-inline-policy-kms-decrypt.js";
import import32 from "./AWS Key Management Service/check-kms-key-rotation.js";
import import33 from "./AWS Key Management Service/check-kms-keys-deletion-status.js";
import import34 from "./AWS Key Management Service/check-kms-public-access.js";
import import35 from "./AWS Lambda/check-aws-config-lambda.js";
import import36 from "./AWS Lambda/check-lambda-code-signing.js";
import import37 from "./AWS Lambda/check-lambda-execution-roles.js";
import import38 from "./AWS Lambda/check-lambda-exposure.js";
import import39 from "./AWS Lambda/check-lambda-insights.js";
import import40 from "./AWS Lambda/check-lambda-least-privilege.js";
import import41 from "./AWS Lambda/check-lambda-privileges.js";
import import42 from "./AWS Lambda/check-lambda-public-access.js";
import import43 from "./AWS Lambda/check-lambda-runtime-versions.js";
import import44 from "./AWS Lambda/check-lambda-runtime.js";
import import45 from "./AWS Lambda/check-lambda-secrets-manager.js";
import import46 from "./AWS Lambda/check-lambda-unique-iam-roles.js";
import import47 from "./AWS Lambda/check-lambda-vpc-multi-az.js";
import import48 from "./AWS Organizations/check-organization-ec2-tag-policies.js";
import import49 from "./AWS Organizations/check-organization-tag-policy.js";
import import50 from "./AWS Security Hub/check-security-hub.js";
import import51 from "./AWS SimSpace Weaver/check-encrypted-communications.js";
import import52 from "./Amazon API Gateway/check-api-gateway-cache-encryption.js";
import import53 from "./Amazon API Gateway/check-api-gateway-logging.js";
import import54 from "./Amazon API Gateway/check-api-gateway-route-authorization.js";
import import55 from "./Amazon API Gateway/check-api-gateway-ssl-certificates.js";
import import56 from "./Amazon API Gateway/check-api-gateway-v2-access-logging.js";
import import57 from "./Amazon API Gateway/check-api-gateway-waf.js";
import import58 from "./Amazon API Gateway/check-api-gateway-xray-tracing.js";
import import59 from "./Amazon Athena/check-athena-catalog-tags.js";
import import60 from "./Amazon Athena/check-athena-workgroup-encryption.js";
import import61 from "./Amazon Athena/check-athena-workgroup-logging.js";
import import62 from "./Amazon Athena/check-athena-workgroup-tags.js";
import import63 from "./Amazon CloudFront/check-cloudfront-custom-origin-encryption.js";
import import64 from "./Amazon CloudFront/check-cloudfront-custom-ssl-certificate.js";
import import65 from "./Amazon CloudFront/check-cloudfront-default-root-object.js";
import import66 from "./Amazon CloudFront/check-cloudfront-distribution-tags.js";
import import67 from "./Amazon CloudFront/check-cloudfront-encryption.js";
import import68 from "./Amazon CloudFront/check-cloudfront-logging.js";
import import69 from "./Amazon CloudFront/check-cloudfront-oac.js";
import import70 from "./Amazon CloudFront/check-cloudfront-origin-failover.js";
import import71 from "./Amazon CloudFront/check-cloudfront-s3-origin.js";
import import72 from "./Amazon CloudFront/check-cloudfront-sni.js";
import import73 from "./Amazon CloudFront/check-cloudfront-ssl-protocols.js";
import import74 from "./Amazon CloudFront/check-cloudfront-waf.js";
import import75 from "./Amazon CloudWatch/aws_cloudwatch_alarm_action_check.js";
import import76 from "./Amazon CloudWatch/aws_cloudwatch_alarm_action_enabled.js";
import import77 from "./Amazon CloudWatch/aws_cloudwatch_cloudtrail.js";
import import78 from "./Amazon CloudWatch/aws_cloudwatch_cmk.js";
import import79 from "./Amazon CloudWatch/aws_cloudwatch_config.js";
import import80 from "./Amazon CloudWatch/aws_cloudwatch_console_auth.js";
import import81 from "./Amazon CloudWatch/aws_cloudwatch_log_group_retention.js";
import import82 from "./Amazon CloudWatch/aws_cloudwatch_monitoring_iam_policies.js";
import import83 from "./Amazon CloudWatch/aws_cloudwatch_monitoring_root_account.js";
import import84 from "./Amazon CloudWatch/aws_cloudwatch_monitoring_signin_mfa.js";
import import85 from "./Amazon CloudWatch/aws_cloudwatch_monitoring_unauthorized_api_calls.js";
import import86 from "./Amazon CloudWatch/aws_cloudwatch_nacl_monitoring.js";
import import87 from "./Amazon CloudWatch/aws_cloudwatch_network_gateway.js";
import import88 from "./Amazon CloudWatch/aws_cloudwatch_org_changes_monitored.js";
import import89 from "./Amazon CloudWatch/aws_cloudwatch_route_table.js";
import import90 from "./Amazon CloudWatch/aws_cloudwatch_s3_policy_change.js";
import import91 from "./Amazon CloudWatch/aws_cloudwatch_security_group.js";
import import92 from "./Amazon CloudWatch/aws_cloudwatch_vpc_changes_monitored.js";
import import93 from "./Amazon DocumentDB/check-docdb-audit-logging.js";
import import94 from "./Amazon DocumentDB/check-docdb-auth-access-control.js";
import import95 from "./Amazon DocumentDB/check-docdb-backup-retention.js";
import import96 from "./Amazon DocumentDB/check-docdb-backup-window.js";
import import97 from "./Amazon DocumentDB/check-docdb-backup.js";
import import98 from "./Amazon DocumentDB/check-docdb-cluster-encryption.js";
import import99 from "./Amazon DocumentDB/check-docdb-deletion-protection.js";
import import100 from "./Amazon DocumentDB/check-docdb-encryption-at-rest.js";
import import101 from "./Amazon DocumentDB/check-docdb-encryption-in-transit.js";
import import102 from "./Amazon DocumentDB/check-docdb-monitoring-alerting.js";
import import103 from "./Amazon DocumentDB/check-docdb-monitoring.js";
import import104 from "./Amazon DocumentDB/check-docdb-security-assessments.js";
import import105 from "./Amazon DocumentDB/check-docdb-snapshot-compliance.js";
import import106 from "./Amazon DocumentDB/check-docdb-subnet-group-acls.js";
import import107 from "./Amazon DocumentDB/check-docdb-updates.js";
import import108 from "./Amazon DynamoDB/check-dax-encryption.js";
import import109 from "./Amazon DynamoDB/check-dynamodb-audit-logging.js";
import import110 from "./Amazon DynamoDB/check-dynamodb-autoscaling.js";
import import111 from "./Amazon DynamoDB/check-dynamodb-deletion-protection.js";
import import112 from "./Amazon DynamoDB/check-dynamodb-encryption.js";
import import113 from "./Amazon DynamoDB/check-dynamodb-fgac.js";
import import114 from "./Amazon DynamoDB/check-dynamodb-iam-access-control.js";
import import115 from "./Amazon DynamoDB/check-dynamodb-pitr.js";
import import116 from "./Amazon DynamoDB/check-dynamodb-stream-compliance.js";
import import117 from "./Amazon DynamoDB/check-dynamodb-vpc-endpoint.js";
import import118 from "./Amazon ElastiCache/check-elasticache-auth-access-control.js";
import import119 from "./Amazon ElastiCache/check-elasticache-auth.js";
import import120 from "./Amazon ElastiCache/check-elasticache-auto-failover.js";
import import121 from "./Amazon ElastiCache/check-elasticache-auto-minor-version-upgrade.js";
import import122 from "./Amazon ElastiCache/check-elasticache-automatic-updates.js";
import import123 from "./Amazon ElastiCache/check-elasticache-encryption-in-transit.js";
import import124 from "./Amazon ElastiCache/check-elasticache-encryption.js";
import import125 from "./Amazon ElastiCache/check-elasticache-logging.js";
import import126 from "./Amazon ElastiCache/check-elasticache-monitoring.js";
import import127 from "./Amazon ElastiCache/check-elasticache-network-security.js";
import import128 from "./Amazon ElastiCache/check-elasticache-secure-access.js";
import import129 from "./Amazon ElastiCache/check-elasticache-subnet-groups.js";
import import130 from "./Amazon ElastiCache/check-elasticache-vpc.js";
import import131 from "./Amazon Elastic Block Store/check-ebs-delete-on-termination.js";
import import132 from "./Amazon Elastic Block Store/check-ebs-snapshot-public-access.js";
import import133 from "./Amazon Elastic Block Store/check-ebs-volume-encryption.js";
import import134 from "./Amazon Elastic Compute Cloud (EC2)/aws_autoscaling_elb_healthcheck_required.js";
import import135 from "./Amazon Elastic Compute Cloud (EC2)/aws_autoscaling_launch_template.js";
import import136 from "./Amazon Elastic Compute Cloud (EC2)/aws_autoscaling_multiple_instance_types.js";
import import137 from "./Amazon Elastic Compute Cloud (EC2)/aws_autoscaling_no_public_ip.js";
import import138 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_ami_encryption.js";
import import139 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_ami_public_acees.js";
import import140 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_autoscaling_propagate_tag.js";
import import141 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_default_security_group.js";
import import142 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_detailed_monitoring.js";
import import143 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_imdsv2.js";
import import144 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_launch_template_imdsv2.js";
import import145 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_launch_template_public_ip.js";
import import146 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_multiple_eni.js";
import import147 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_no_public_ip.js";
import import148 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_no_secrets_in_user_data.js";
import import149 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_subnet_auto_assign_public_ip.js";
import import150 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_systems_manager.js";
import import151 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_vpc_endpoint.js";
import import152 from "./Amazon Elastic Compute Cloud (EC2)/aws_security_group_authorized_ports.js";
import import153 from "./Amazon Elastic Compute Cloud (EC2)/aws_security_group_high_risk_ports.js";
import import154 from "./Amazon Elastic Compute Cloud (EC2)/aws_transit_gateway_auto_accept_disabled.js";
import import155 from "./Amazon Elastic Compute Cloud (EC2)/check-ec2-instance-age.js";
import import156 from "./Amazon Elastic Compute Cloud (EC2)/check-stopped-instances.js";
import import157 from "./Amazon Elastic Compute Cloud (EC2)/check-unused-enis.js";
import import158 from "./Amazon Elastic Container Registry/check-ecr-image-scanning.js";
import import159 from "./Amazon Elastic Container Registry/check-ecr-lifecycle-policy.js";
import import160 from "./Amazon Elastic Container Registry/check-ecr-tag-immutability.js";
import import161 from "./Amazon Elastic Container Registry/check-ecs-container-insights.js";
import import162 from "./Amazon Elastic Container Registry/check-ecs-container-privileges.js";
import import163 from "./Amazon Elastic Container Registry/check-ecs-container-readonly-root.js";
import import164 from "./Amazon Elastic Container Registry/check-ecs-fargate-platform-version.js";
import import165 from "./Amazon Elastic Container Registry/check-ecs-public-ip.js";
import import166 from "./Amazon Elastic Container Registry/check-ecs-secret-env-vars.js";
import import167 from "./Amazon Elastic Container Registry/check-ecs-task-definition-logging.js";
import import168 from "./Amazon Elastic Container Registry/check-ecs-task-definition-pid-mode.js";
import import169 from "./Amazon Elastic Container Registry/check-ecs-task-public-ip.js";
import import170 from "./Amazon Elastic Container Registry/check-ecs-task-security.js";
import import171 from "./Amazon Elastic File System/aws_efs_access_points_enforce_root_directory.js";
import import172 from "./Amazon Elastic File System/aws_efs_access_points_enforce_user_identity.js";
import import173 from "./Amazon Elastic File System/aws_efs_file_system_kms_encryption.js";
import import174 from "./Amazon Elastic File System/aws_efs_mount_targets_not_public.js";
import import175 from "./Amazon Identity and Access Management/aws_iam_access_analyzer.js";
import import176 from "./Amazon Identity and Access Management/aws_iam_account_password_policy.js";
import import177 from "./Amazon Identity and Access Management/aws_iam_centralized_management.js";
import import178 from "./Amazon Identity and Access Management/aws_iam_cloudshell_access.js";
import import179 from "./Amazon Identity and Access Management/aws_iam_instance_roles.js";
import import180 from "./Amazon Identity and Access Management/aws_iam_no_full_admin.js";
import import181 from "./Amazon Identity and Access Management/aws_iam_no_initial_access_keys.js";
import import182 from "./Amazon Identity and Access Management/aws_iam_no_wildcard_actions.js";
import import183 from "./Amazon Identity and Access Management/aws_iam_password_reuse_prevention.js";
import import184 from "./Amazon Identity and Access Management/aws_iam_support_role.js";
import import185 from "./Amazon Identity and Access Management/aws_iam_users_no_direct_policies.js";
import import186 from "./Amazon Identity and Access Management/aws_iam_users_permissions_through_group.js";
import import187 from "./Amazon Identity and Access Management/check-access-key-rotation.js";
import import188 from "./Amazon Identity and Access Management/check-expired-certificates.js";
import import189 from "./Amazon Identity and Access Management/check-iam-access-keys.js";
import import190 from "./Amazon Identity and Access Management/check-iam-mfa.js";
import import191 from "./Amazon Identity and Access Management/check-unused-credentials.js";
import import192 from "./Amazon Keyspaces (for Apache Cassandra)/check-keyspace-security.js";
import import193 from "./Amazon Keyspaces (for Apache Cassandra)/check-keyspaces-encryption-transit.js";
import import194 from "./Amazon Keyspaces (for Apache Cassandra)/check-keyspaces-network-security.js";
import import195 from "./Amazon Lightsail/check-lightsail-bucket-access.js";
import import196 from "./Amazon Machine Image/check-ami-age.js";
import import197 from "./Amazon Machine Image/check-ami-encryption.js";
import import198 from "./Amazon Machine Image/check-approved-amis.js";
import import199 from "./Amazon Machine Image/check-public-amis.js";
import import200 from "./Amazon MemoryDB/check-memorydb-acl.js";
import import201 from "./Amazon MemoryDB/check-memorydb-encryption-at-rest.js";
import import202 from "./Amazon MemoryDB/check-memorydb-encryption-in-transit.js";
import import203 from "./Amazon MemoryDB/check-memorydb-monitoring.js";
import import204 from "./Amazon MemoryDB/check-memorydb-network-security.js";
import import205 from "./Amazon Neptune/check-neptune-access-control.js";
import import206 from "./Amazon Neptune/check-neptune-alerting.js";
import import207 from "./Amazon Neptune/check-neptune-audit-logging.js";
import import208 from "./Amazon Neptune/check-neptune-encryption.js";
import import209 from "./Amazon Neptune/check-neptune-network-security.js";
import import210 from "./Amazon Relational Database Service/check-aurora-access-key-rotation.js";
import import211 from "./Amazon Relational Database Service/check-aurora-audit-logging.js";
import import212 from "./Amazon Relational Database Service/check-aurora-backtracking.js";
import import213 from "./Amazon Relational Database Service/check-aurora-backup-compliance.js";
import import214 from "./Amazon Relational Database Service/check-aurora-encryption-in-transit.js";
import import215 from "./Amazon Relational Database Service/check-aurora-encryption.js";
import import216 from "./Amazon Relational Database Service/check-aurora-iam-roles-and-policies.js";
import import217 from "./Amazon Relational Database Service/check-aurora-least-privilege.js";
import import218 from "./Amazon Relational Database Service/check-aurora-mysql-cloudwatch-logs.js";
import import219 from "./Amazon Relational Database Service/check-aurora-postgres-cloudwatch-logs.js";
import import220 from "./Amazon Relational Database Service/check-neptune-audit-logs.js";
import import221 from "./Amazon Relational Database Service/check-neptune-automated-backups.js";
import import222 from "./Amazon Relational Database Service/check-neptune-cluster-encryption.js";
import import223 from "./Amazon Relational Database Service/check-neptune-copy-tags-to-snapshot.js";
import import224 from "./Amazon Relational Database Service/check-neptune-deletion-protection.js";
import import225 from "./Amazon Relational Database Service/check-neptune-iam-auth.js";
import import226 from "./Amazon Relational Database Service/check-neptune-snapshots-encryption.js";
import import227 from "./Amazon Relational Database Service/check-rds-access-control-authentication.js";
import import228 from "./Amazon Relational Database Service/check-rds-auto-minor-version-upgrade.js";
import import229 from "./Amazon Relational Database Service/check-rds-automated-backups.js";
import import230 from "./Amazon Relational Database Service/check-rds-backup-enabled.js";
import import231 from "./Amazon Relational Database Service/check-rds-cloudwatch-logs.js";
import import232 from "./Amazon Relational Database Service/check-rds-cluster-deletion-protection.js";
import import233 from "./Amazon Relational Database Service/check-rds-cluster-encryption.js";
import import234 from "./Amazon Relational Database Service/check-rds-cluster-iam-auth.js";
import import235 from "./Amazon Relational Database Service/check-rds-cluster-multi-az.js";
import import236 from "./Amazon Relational Database Service/check-rds-cluster-tag.js";
import import237 from "./Amazon Relational Database Service/check-rds-custom-admin-username.js";
import import238 from "./Amazon Relational Database Service/check-rds-database-security.js";
import import239 from "./Amazon Relational Database Service/check-rds-default-ports.js";
import import240 from "./Amazon Relational Database Service/check-rds-deletion-protection.js";
import import241 from "./Amazon Relational Database Service/check-rds-encryption-at-rest.js";
import import242 from "./Amazon Relational Database Service/check-rds-encryption-in-transit.js";
import import243 from "./Amazon Relational Database Service/check-rds-enhanced-monitoring.js";
import import244 from "./Amazon Relational Database Service/check-rds-event-notifications.js";
import import245 from "./Amazon Relational Database Service/check-rds-event-subscription-parameter-group.js";
import import246 from "./Amazon Relational Database Service/check-rds-event-subscriptions.js";
import import247 from "./Amazon Relational Database Service/check-rds-iam-auth.js";
import import248 from "./Amazon Relational Database Service/check-rds-in-vpc.js";
import import249 from "./Amazon Relational Database Service/check-rds-instances-in-vpc.js";
import import250 from "./Amazon Relational Database Service/check-rds-monitoring-logging.js";
import import251 from "./Amazon Relational Database Service/check-rds-multi-az.js";
import import252 from "./Amazon Relational Database Service/check-rds-password-rotation.js";
import import253 from "./Amazon Relational Database Service/check-rds-postgres-cloudwatch-logs.js";
import import254 from "./Amazon Relational Database Service/check-rds-public-access.js";
import import255 from "./Amazon Relational Database Service/check-rds-security-group-event-notifications.js";
import import256 from "./Amazon Relational Database Service/check-rds-security-groups-configured.js";
import import257 from "./Amazon Relational Database Service/check-rds-security-groups.js";
import import258 from "./Amazon Relational Database Service/check-rds-snapshot-encryption.js";
import import259 from "./Amazon Relational Database Service/check-rds-snapshots-private.js";
import import260 from "./Amazon Relational Database Service/check-rds-tag-copy-compliance.js";
import import261 from "./Amazon Relational Database Service/check-vpc-exists.js";
import import262 from "./Amazon Simple Storage Service (Amazon S3)/aws_s3_http_access_deny.js";
import import263 from "./Amazon Simple Storage Service (Amazon S3)/aws_s3_mfa_delete_enabled.js";
import import264 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-access-point-block-public-access.js";
import import265 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-block-public-access.js";
import import266 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-bucket-acl-compliance.js";
import import267 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-bucket-external-access.js";
import import268 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-bucket-lifecycle-configuration.js";
import import269 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-bucket-logging.js";
import import270 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-data-discovery-compliance.js";
import import271 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-deny-http-access.js";
import import272 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-mfa-delete.js";
import import273 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-object-level-logging.js";
import import274 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-object-read-logging.js";
import import275 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-ssl-required.js";
import import276 from "./Amazon Timestream for LiveAnalytics/check-timestream-access-control.js";
import import277 from "./Amazon Timestream for LiveAnalytics/check-timestream-audit-logging.js";
import import278 from "./Amazon Timestream for LiveAnalytics/check-timestream-fine-grained-access.js";
import import279 from "./Amazon Timestream for LiveAnalytics/check-timestream-monitoring.js";
import import280 from "./Amazon Virtual Private Cloud/check-default-security-group-compliance.js";
import import281 from "./Amazon Virtual Private Cloud/check-nacl-port22-compliance.js";
import import282 from "./Amazon Virtual Private Cloud/check-security-group-admin-ports.js";
import import283 from "./Amazon Virtual Private Cloud/check-vpc-flow-logs.js";
import import284 from "./Amazon Virtual Private Cloud/check-vpc-peering-routing-compliance.js";

export default [
    import0,
    import1,
    import2,
    import3,
    import4,
    import5,
    import6,
    import7,
    import8,
    import9,
    import10,
    import11,
    import12,
    import13,
    import14,
    import15,
    import16,
    import17,
    import18,
    import19,
    import20,
    import21,
    import22,
    import23,
    import24,
    import25,
    import26,
    import27,
    import28,
    import29,
    import30,
    import31,
    import32,
    import33,
    import34,
    import35,
    import36,
    import37,
    import38,
    import39,
    import40,
    import41,
    import42,
    import43,
    import44,
    import45,
    import46,
    import47,
    import48,
    import49,
    import50,
    import51,
    import52,
    import53,
    import54,
    import55,
    import56,
    import57,
    import58,
    import59,
    import60,
    import61,
    import62,
    import63,
    import64,
    import65,
    import66,
    import67,
    import68,
    import69,
    import70,
    import71,
    import72,
    import73,
    import74,
    import75,
    import76,
    import77,
    import78,
    import79,
    import80,
    import81,
    import82,
    import83,
    import84,
    import85,
    import86,
    import87,
    import88,
    import89,
    import90,
    import91,
    import92,
    import93,
    import94,
    import95,
    import96,
    import97,
    import98,
    import99,
    import100,
    import101,
    import102,
    import103,
    import104,
    import105,
    import106,
    import107,
    import108,
    import109,
    import110,
    import111,
    import112,
    import113,
    import114,
    import115,
    import116,
    import117,
    import118,
    import119,
    import120,
    import121,
    import122,
    import123,
    import124,
    import125,
    import126,
    import127,
    import128,
    import129,
    import130,
    import131,
    import132,
    import133,
    import134,
    import135,
    import136,
    import137,
    import138,
    import139,
    import140,
    import141,
    import142,
    import143,
    import144,
    import145,
    import146,
    import147,
    import148,
    import149,
    import150,
    import151,
    import152,
    import153,
    import154,
    import155,
    import156,
    import157,
    import158,
    import159,
    import160,
    import161,
    import162,
    import163,
    import164,
    import165,
    import166,
    import167,
    import168,
    import169,
    import170,
    import171,
    import172,
    import173,
    import174,
    import175,
    import176,
    import177,
    import178,
    import179,
    import180,
    import181,
    import182,
    import183,
    import184,
    import185,
    import186,
    import187,
    import188,
    import189,
    import190,
    import191,
    import192,
    import193,
    import194,
    import195,
    import196,
    import197,
    import198,
    import199,
    import200,
    import201,
    import202,
    import203,
    import204,
    import205,
    import206,
    import207,
    import208,
    import209,
    import210,
    import211,
    import212,
    import213,
    import214,
    import215,
    import216,
    import217,
    import218,
    import219,
    import220,
    import221,
    import222,
    import223,
    import224,
    import225,
    import226,
    import227,
    import228,
    import229,
    import230,
    import231,
    import232,
    import233,
    import234,
    import235,
    import236,
    import237,
    import238,
    import239,
    import240,
    import241,
    import242,
    import243,
    import244,
    import245,
    import246,
    import247,
    import248,
    import249,
    import250,
    import251,
    import252,
    import253,
    import254,
    import255,
    import256,
    import257,
    import258,
    import259,
    import260,
    import261,
    import262,
    import263,
    import264,
    import265,
    import266,
    import267,
    import268,
    import269,
    import270,
    import271,
    import272,
    import273,
    import274,
    import275,
    import276,
    import277,
    import278,
    import279,
    import280,
    import281,
    import282,
    import283,
    import284
];