/* eslint-disable */
/**
 * This file is auto-generated by the "bun generate-runtime-index" command.
 * Do not modify this file directly.
 */
import import0 from "./AWS Security Hub/check-security-hub.ts";
import import1 from "./AWS CloudTrail/check-cloudtrail-log-validation.ts";
import import2 from "./AWS CloudTrail/check-cloudtrail-enabled.ts";
import import3 from "./AWS CloudTrail/check-cloudtrail-s3-access-logging.ts";
import import4 from "./AWS CloudTrail/check-cloudtrail-kms-encryption.ts";
import import5 from "./AWS CloudTrail/check-cloudtrail-tagged.ts";
import import6 from "./AWS CloudTrail/check-cloudtrail-multiregion.ts";
import import7 from "./AWS CloudTrail/check-cloudtrail-encryption.ts";
import import8 from "./Amazon CloudWatch/aws_cloudwatch_vpc_changes_monitored.ts";
import import9 from "./Amazon CloudWatch/aws_cloudwatch_console_auth.ts";
import import10 from "./Amazon CloudWatch/aws_cloudwatch_monitoring_signin_mfa.ts";
import import11 from "./Amazon CloudWatch/aws_cloudwatch_route_table.ts";
import import12 from "./Amazon CloudWatch/aws_cloudwatch_cloudtrail.ts";
import import13 from "./Amazon CloudWatch/aws_cloudwatch_monitoring_root_account.ts";
import import14 from "./Amazon CloudWatch/aws_cloudwatch_alarm_action_enabled.ts";
import import15 from "./Amazon CloudWatch/aws_cloudwatch_cmk.ts";
import import16 from "./Amazon CloudWatch/aws_cloudwatch_security_group.ts";
import import17 from "./Amazon CloudWatch/aws_cloudwatch_nacl_monitoring.ts";
import import18 from "./Amazon CloudWatch/aws_cloudwatch_s3_policy_change.ts";
import import19 from "./Amazon CloudWatch/aws_cloudwatch_monitoring_unauthorized_api_calls.ts";
import import20 from "./Amazon CloudWatch/aws_cloudwatch_alarm_action_check.ts";
import import21 from "./Amazon CloudWatch/aws_cloudwatch_log_group_retention.ts";
import import22 from "./Amazon CloudWatch/aws_cloudwatch_network_gateway.ts";
import import23 from "./Amazon CloudWatch/aws_cloudwatch_org_changes_monitored.ts";
import import24 from "./Amazon CloudWatch/aws_cloudwatch_config.ts";
import import25 from "./Amazon CloudWatch/aws_cloudwatch_monitoring_iam_policies.ts";
import import26 from "./AWS Config/check-config-enabled-all-regions.ts";
import import27 from "./Amazon Virtual Private Cloud/check-default-security-group-compliance.ts";
import import28 from "./Amazon Virtual Private Cloud/check-vpc-peering-routing-compliance.ts";
import import29 from "./Amazon Virtual Private Cloud/check-nacl-port22-compliance.ts";
import import30 from "./Amazon Virtual Private Cloud/check-security-group-admin-ports.ts";
import import31 from "./Amazon Virtual Private Cloud/check-vpc-flow-logs.ts";
import import32 from "./Amazon Elastic Container Registry/check-ecs-container-insights.ts";
import import33 from "./Amazon Elastic Container Registry/check-ecr-image-scanning.ts";
import import34 from "./Amazon Elastic Container Registry/check-ecs-container-readonly-root.ts";
import import35 from "./Amazon Elastic Container Registry/check-ecr-tag-immutability.ts";
import import36 from "./Amazon Elastic Container Registry/check-ecr-lifecycle-policy.ts";
import import37 from "./AWS Key Management Service/check-kms-key-rotation.ts";
import import38 from "./AWS Key Management Service/check-kms-public-access.ts";
import import39 from "./AWS Key Management Service/check-kms-keys-deletion-status.ts";
import import40 from "./AWS Key Management Service/check-iam-kms-decrypt-policy.ts";
import import41 from "./AWS Key Management Service/check-inline-policy-kms-decrypt.ts";
import import42 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-data-discovery-compliance.ts";
import import43 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-object-level-logging.ts";
import import44 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-block-public-access.ts";
import import45 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-object-read-logging.ts";
import import46 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-deny-http-access.ts";
import import47 from "./Amazon Simple Storage Service (Amazon S3)/aws_s3_http_access_deny.ts";
import import48 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-bucket-external-access.ts";
import import49 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-mfa-delete.ts";
import import50 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-bucket-acl-compliance.ts";
import import51 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-bucket-logging.ts";
import import52 from "./Amazon Simple Storage Service (Amazon S3)/aws_s3_mfa_delete_enabled.ts";
import import53 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-ssl-required.ts";
import import54 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-access-point-block-public-access.ts";
import import55 from "./Amazon Simple Storage Service (Amazon S3)/check-s3-bucket-lifecycle-configuration.ts";
import import56 from "./Amazon Identity and Access Management/aws_iam_centralized_management.ts";
import import57 from "./Amazon Identity and Access Management/aws_iam_no_wildcard_actions.ts";
import import58 from "./Amazon Identity and Access Management/aws_iam_users_no_direct_policies.ts";
import import59 from "./Amazon Identity and Access Management/aws_iam_no_initial_access_keys.ts";
import import60 from "./Amazon Identity and Access Management/aws_iam_support_role.ts";
import import61 from "./Amazon Identity and Access Management/aws_iam_instance_roles.ts";
import import62 from "./Amazon Identity and Access Management/aws_iam_users_permissions_through_group.ts";
import import63 from "./Amazon Identity and Access Management/aws_iam_cloudshell_access.ts";
import import64 from "./Amazon Identity and Access Management/aws_iam_account_password_policy.ts";
import import65 from "./Amazon Identity and Access Management/aws_iam_access_analyzer.ts";
import import66 from "./Amazon Identity and Access Management/aws_iam_password_reuse_prevention.ts";
import import67 from "./Amazon Identity and Access Management/aws_iam_no_full_admin.ts";
import import68 from "./Amazon Elastic File System/aws_efs_access_points_enforce_root_directory.ts";
import import69 from "./Amazon Elastic File System/aws_efs_mount_targets_not_public.ts";
import import70 from "./Amazon Elastic File System/aws_efs_access_points_enforce_user_identity.ts";
import import71 from "./Amazon Elastic File System/aws_efs_file_system_kms_encryption.ts";
import import72 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_launch_template_public_ip.ts";
import import73 from "./Amazon Elastic Compute Cloud (EC2)/aws_autoscaling_elb_healthcheck_required.ts";
import import74 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_detailed_monitoring.ts";
import import75 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_systems_manager.ts";
import import76 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_launch_template_imdsv2.ts";
import import77 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_default_security_group.ts";
import import78 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_subnet_auto_assign_public_ip.ts";
import import79 from "./Amazon Elastic Compute Cloud (EC2)/aws_autoscaling_no_public_ip.ts";
import import80 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_autoscaling_propagate_tag.ts";
import import81 from "./Amazon Elastic Compute Cloud (EC2)/aws_security_group_authorized_ports.ts";
import import82 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_ami_encryption.ts";
import import83 from "./Amazon Elastic Compute Cloud (EC2)/aws_autoscaling_launch_template.ts";
import import84 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_no_public_ip.ts";
import import85 from "./Amazon Elastic Compute Cloud (EC2)/aws_security_group_high_risk_ports.ts";
import import86 from "./Amazon Elastic Compute Cloud (EC2)/aws_transit_gateway_auto_accept_disabled.ts";
import import87 from "./Amazon Elastic Compute Cloud (EC2)/aws_autoscaling_multiple_instance_types.ts";
import import88 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_vpc_endpoint.ts";
import import89 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_imdsv2.ts";
import import90 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_multiple_eni.ts";
import import91 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_ami_public_acees.ts";
import import92 from "./Amazon Elastic Compute Cloud (EC2)/aws_ec2_no_secrets_in_user_data.ts";

export default [
    import0,
    import1,
    import2,
    import3,
    import4,
    import5,
    import6,
    import7,
    import8,
    import9,
    import10,
    import11,
    import12,
    import13,
    import14,
    import15,
    import16,
    import17,
    import18,
    import19,
    import20,
    import21,
    import22,
    import23,
    import24,
    import25,
    import26,
    import27,
    import28,
    import29,
    import30,
    import31,
    import32,
    import33,
    import34,
    import35,
    import36,
    import37,
    import38,
    import39,
    import40,
    import41,
    import42,
    import43,
    import44,
    import45,
    import46,
    import47,
    import48,
    import49,
    import50,
    import51,
    import52,
    import53,
    import54,
    import55,
    import56,
    import57,
    import58,
    import59,
    import60,
    import61,
    import62,
    import63,
    import64,
    import65,
    import66,
    import67,
    import68,
    import69,
    import70,
    import71,
    import72,
    import73,
    import74,
    import75,
    import76,
    import77,
    import78,
    import79,
    import80,
    import81,
    import82,
    import83,
    import84,
    import85,
    import86,
    import87,
    import88,
    import89,
    import90,
    import91,
    import92
];