/* eslint-disable */
/**
 * This file is auto-generated by the "npm run generate-runtime-index" command.
 * Do not modify this file directly.
 */
import import0 from "./API Gateway/gcp-active-api-keys.js";
import import1 from "./API Gateway/gcp-api-key-app-restrictions.js";
import import2 from "./API Gateway/gcp_api_key_restrictions.js";
import import3 from "./Access Approval/gcp-access-approval.js";
import import4 from "./Cloud Asset Inventory/gcp-cloud-asset-inventory.js";
import import5 from "./Cloud DNS/gcp-dnssec-algorithm.js";
import import6 from "./Cloud DNS/gcp-dnssec-enabled.js";
import import7 from "./Cloud DNS/gcp-dnssec-key-algorithm.js";
import import8 from "./Cloud IAM/gcp_audit_logging_configured.js";
import import9 from "./Cloud IAM/gcp_service_account_admin_check.js";
import import10 from "./Google Compute Engine/gcp-ip-forwarding-disabled.js";
import import11 from "./Google Compute Engine/gcp_block_project_ssh_keys.js";
import import12 from "./Google Compute Engine/gcp_compute_default_service_account.js";
import import13 from "./Google Compute Engine/gcp_compute_no_public_ip.js";
import import14 from "./Google Compute Engine/gcp_confidential_computing.js";
import import15 from "./Google Compute Engine/gcp_disk_csek_encryption.js";
import import16 from "./Google Compute Engine/gcp_ip_forwarding_disabled.js";
import import17 from "./Google Compute Engine/gcp_oslogin_enabled.js";
import import18 from "./Google Compute Engine/gcp_shielded_vm_enabled.js";
import import19 from "./Google Compute Engine/gcp_vm_serial_ports_disabled.js";
import import20 from "./Google Virtual Private Cloud/gcp_no_default_network.js";
import import21 from "./Google Virtual Private Cloud/gcp_rdp_restricted.js";
import import22 from "./Google Virtual Private Cloud/gcp_ssh_restricted.js";
import import23 from "./Google Virtual Private Cloud/gcp_vpc_flow_logs_enabled.js";

export default [
    import0,
    import1,
    import2,
    import3,
    import4,
    import5,
    import6,
    import7,
    import8,
    import9,
    import10,
    import11,
    import12,
    import13,
    import14,
    import15,
    import16,
    import17,
    import18,
    import19,
    import20,
    import21,
    import22,
    import23
];