name: Release

permissions:
  contents: write
  pull-requests: write
  packages: write
  checks: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g., 1.0.0)"
        required: true
        type: string
      publish_npm_package:
        description: "Publish npm package"
        required: true
        default: true
        type: boolean

defaults:
  run:
    working-directory: cli

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: cd .. && npm ci && cd cli && cp ../package-lock.json .

      - name: Update version
        run: |
          VERSION=${{ github.event.inputs.version }}
          BRANCH="release/v${VERSION}"

          # Create and checkout new branch
          git checkout -b $BRANCH

          # Update version and generate files
          npm version $VERSION --no-git-tag-version
          npm run generate

          # Configure git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Commit changes
          git add .
          git commit -m "chore: bump version to ${VERSION}"

          # Push branch
          git push origin $BRANCH --force

          PR_URL="$(gh pr list --head "${BRANCH}" --state open --json url --jq .[].url)"

          # Only create a PR if one doesn't already exist
          if [ -z "$PR_URL" ]; then
            gh pr create \
              --title "Release v${VERSION}" \
              --body "This PR bumps the version to ${VERSION}" \
              --base main \
              --head $BRANCH
          fi

          # Create and push tag
          git tag "v${VERSION}" --force
          git push origin tag "v${VERSION}" --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check publish_npm_package value
        run: echo "publish_npm_package ${{ github.event.inputs.publish_npm_package }}"

      - name: Publish to npm
        if: ${{ github.event.inputs.publish_npm_package == true }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-packages:
    needs: release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: deb
            path: "cli/dist/deb/*.deb"
          - os: macos-latest
            target: macos
            path: "cli/dist/macos/*.pkg"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ github.event.inputs.version }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"

      - name: Install NSIS and 7zip (for deb package)
        if: matrix.target == 'deb'
        run: |
          sudo apt-get update
          sudo apt-get install -y nsis p7zip-full apt-utils

      - name: Set up Homebrew
        if: matrix.target == 'macos'
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install NSIS and 7zip (for macos)
        if: matrix.target == 'macos'
        run: |
          brew install p7zip nsis

      - name: Install dependencies
        run: cd .. && npm ci && cd cli && cp ../package-lock.json .

      - name: Build starkit
        run: npm run build

      - name: Build OCLIF package
        run: npx -y oclif pack ${{ matrix.target }}

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-package
          path: ${{ matrix.path }}
          if-no-files-found: error

  build-tarballs:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ github.event.inputs.version }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"

      - name: Install NSIS and 7zip
        run: |
          sudo apt-get update
          sudo apt-get install -y nsis p7zip-full

      - name: Install dependencies
        run: cd .. && npm ci && cd cli && cp ../package-lock.json .

      - name: Build starkit
        run: npm run build

      - name: Build OCLIF tarballs
        run: npx -y oclif pack tarballs --parallel --targets=linux-x64,linux-arm64,win32-x64,darwin-x64,darwin-arm64

      - name: Push OCLIF tarballs to S3
        run: npx -y oclif upload tarballs --targets=linux-x64,linux-arm64,win32-x64,darwin-x64,darwin-arm64

      - name: Push OCLIF tarballs to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tarballs
          path: cli/dist/*.xz
          if-no-files-found: error

  build-windows:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ github.event.inputs.version }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"

      - name: Install NSIS and 7zip
        run: |
          sudo apt-get update
          sudo apt-get install -y nsis p7zip-full

      - name: Install dependencies
        run: cd .. && npm ci && cd cli && cp ../package-lock.json .

      - name: Build starkit
        run: npm run build

      - name: Build Windows installer
        run: npx -y oclif pack win --targets=win32-x64

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: cli/dist/win32/*.exe
          if-no-files-found: error

  create-release:
    needs: [build-packages, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: v${{ github.event.inputs.version }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # @todo - @pranaySinghDev - Uncomment this block if you want to update Homebrew formula
  # update-homebrew:
  #   needs: create-release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Update Homebrew formula
  #       uses: dawidd6/action-homebrew-bump-formula@v3
  #       with:
  #         token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
  #         formula: your-cli-name # Replace with your CLI's formula name
