name: Publish Cloudguard to NPM

permissions:
  contents: write
  pull-requests: write
  packages: write
  checks: write

on:
  workflow_dispatch:
    inputs:
      commit-message:
        description: "Commit message for version bump"
        required: true
        default: "chore: bump version"

jobs:
  bump-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
          registry-url: "https://registry.npmjs.org"

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Bump version (minor)
        id: bump-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="$MAJOR.$NEW_MINOR.0"

          # Update version in package.json
          npm version $NEW_VERSION --no-git-tag-version

          # Store new version for later steps
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "VERSION_UPDATED=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create branch for PR
        run: |
          BRANCH_NAME="version-bump-${{ env.NEW_VERSION }}"
          git checkout -b $BRANCH_NAME
          git add package.json
          git commit -m "${{ github.event.inputs.commit-message }}"
          git push -u origin $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE="Bump version to ${{ env.NEW_VERSION }}"
          PR_BODY="This PR bumps the package version to ${{ env.NEW_VERSION }}."
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head ${{ env.BRANCH_NAME }}
